#!/usr/bin/env node
/**
 * Render a branded, comprehensive sitemap from the BUILT publish/ tree.
 *
 * It walks publish/ at build time, so it lists every page + API/data artifact
 * that actually shipped — it can't drift from reality. Writes
 * publish/sitemap/index.html. Run LAST in the build (after all pages exist).
 *
 * Run: node netlify/render_sitemap.js <repo-root>
 */
const fs = require("fs");
const path = require("path");
const { docHead, sidebar } = require("./dashboard_theme");

function esc(s) {
  return String(s == null ? "" : s).replace(
    /[&<>"']/g,
    (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]
  );
}

function walk(dir, base, out) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const fp = path.join(dir, e.name);
    if (e.isDirectory()) walk(fp, base, out);
    else out.push(path.relative(base, fp).split(path.sep).join("/"));
  }
  return out;
}

// Friendly labels for the known human-facing pages.
function labelFor(rel) {
  const known = {
    "index.html": "Dashboard — research trends (home)",
    "sitemap/index.html": "Sitemap",
    "issues/index.html": "Issues archive",
    "newsletter/default.html": "Current newsletter — default brief",
    "newsletter/marketing-activity-30d.html": "Research activity log (30d)",
  };
  if (known[rel]) return known[rel];
  let m = rel.match(/^issues\/(\d{4}-\d{2})\/default\.html$/);
  if (m) return `Issue ${m[1]} — research roundup`;
  m = rel.match(/^issues\/(\d{4}-\d{2})\/marketing-activity-30d\.html$/);
  if (m) return `Issue ${m[1]} — activity log`;
  return rel.replace(/\/index\.html$/, "/").replace(/\.html$/, "");
}

// Link to clean directory URLs where there's an index.html.
function hrefFor(rel) {
  return "../" + rel.replace(/(^|\/)index\.html$/, "$1");
}

function linkList(items, withLabel) {
  if (!items.length) return `<p class="empty">None.</p>`;
  return `<ul class="linklist">${items
    .map((rel) => {
      const href = hrefFor(rel);
      const left = withLabel ? esc(labelFor(rel)) : `<code>${esc("/" + rel)}</code>`;
      const right = withLabel ? `<span class="path">/${esc(rel)}</span>` : "";
      return `<li><a href="${href}">${left}</a>${right}</li>`;
    })
    .join("")}</ul>`;
}

function render(root) {
  const publishDir = path.join(root, "publish");
  const all = walk(publishDir, publishDir, []).sort();

  const pages = all.filter((r) => r.endsWith(".html"));
  const api = all.filter((r) => r.startsWith("api/"));
  const data = all.filter((r) => r.startsWith("data/") && r.endsWith(".json"));
  const other = all.filter(
    (r) =>
      !r.endsWith(".html") &&
      !r.startsWith("api/") &&
      !(r.startsWith("data/") && r.endsWith(".json")) &&
      !r.startsWith("history/") &&
      r !== ".nojekyll"
  );

  // Human pages first (ordered), then the rest of the .html alphabetically.
  const order = [
    "index.html",
    "issues/index.html",
    "newsletter/default.html",
    "newsletter/marketing-activity-30d.html",
    "sitemap/index.html",
  ];
  const primary = order.filter((p) => pages.includes(p));
  const issuePages = pages.filter((p) => /^issues\/\d{4}-\d{2}\//.test(p));
  const otherPages = pages.filter((p) => !primary.includes(p) && !issuePages.includes(p));

  return `<!doctype html>
<html lang="en"><head>
${docHead("Everpure Research — Sitemap")}
</head>
<body>
${sidebar("sitemap", "../")}
<div class="shell"><div class="wrap">
<header>
  <h1>Sitemap</h1>
  <p class="sub">Every page and data endpoint published by the build — generated by scanning the site, so it stays comprehensive.</p>
</header>

<section class="panel">
  <h2>Pages</h2>
  <p class="desc">The human-facing pages.</p>
  ${linkList(primary, true)}
</section>

<section class="panel">
  <h2>Published issues &amp; archives</h2>
  <p class="desc">Frozen monthly issues and per-issue artifacts.</p>
  ${linkList(issuePages, true)}
</section>

${
  otherPages.length
    ? `<section class="panel">
  <h2>Other pages</h2>
  <p class="desc">Section indexes and additional generated pages.</p>
  ${linkList(otherPages, true)}
</section>`
    : ""
}

<section class="panel">
  <h2>API endpoints</h2>
  <p class="desc">Static JSON/Markdown served under <code>/api/</code>.</p>
  ${linkList(api, false)}
</section>

<section class="panel">
  <h2>Data artifacts</h2>
  <p class="desc">Build outputs under <code>/data/</code> (the deterministic evidence substrate).</p>
  ${linkList(data, false)}
</section>

${other.length ? `<section class="panel"><h2>Other</h2>${linkList(other, false)}</section>` : ""}

<footer>Generated by <code>render_sitemap.js</code> from the built <code>publish/</code> tree — ${pages.length} pages, ${api.length} API files, ${data.length} data files.</footer>
</div></div></body></html>`;
}

function main() {
  const root = path.resolve(process.argv[2] || ".");
  const outDir = path.join(root, "publish", "sitemap");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "index.html"), render(root), "utf8");
  console.log(`Wrote ${path.join(outDir, "index.html")}`);
}

if (require.main === module) main();

module.exports = { render, labelFor, hrefFor, walk };
